### ISSUE TITLE
Not able to navigate within Intellij to dependent project source

### ISSUE THREAD

**Issue by BusyByte** [Banno/banno-sbt-plugin#109]
In IntelliJ Idea you should be able to command click on any class in a dependent project and go to the source.
For example if I'm in the project1 and I'm looking at at the class Foo from project2 I should be able to just command click on the class and go to the source. 

Right now it is not working because the banno-sbt-plugin does not publish compile sources.

To make this work we'll need to remove this line:
https://github.com/Banno/banno-sbt-plugin/blob/master/src/main/scala/BannoSettings.scala#L19

We may also want to configure how many days worth of Snapshots we retain in Nexus.

- [X]  [Pr 110](https://github.com/Banno/banno-sbt-plugin/pull/110)

**Comment by adamdecaf** [comment]
Do we know what the storage space needed for the source jars?

**Comment by BusyByte** [comment]
@adamdecaf By looking at the apache commons-lang it looks like the sources jar is slightly bigger than the binary jar.
487 vs 435 KB

I can spot check some of projects but it seems like they should trend the same way as it's just text compression.

**Comment by sherzberg** [comment]
I have wanted this too.

**Comment by adamdecaf** [comment]
:+1: We might want to be safe and add some space to nexus before pushing this change. @BusyByte Want to get a PR out for this?

**Comment by rubbish** [comment]
@BusyByte @adamdecaf We already do clean up snapshots on nexus:

<img width="588" alt="screenshot 2015-10-29 10 10 23" src="https://cloud.githubusercontent.com/assets/1580/10822445/4ad1c2be-7e25-11e5-9eb5-89451b562f12.png">

**Comment by rubbish** [comment]
I'm totally fine removing that packageSrc line so that we publish source jars.

**Comment by BusyByte** [comment]
pr is merged, closing
